/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef NRG_PRIOEXECUTION_H
#define NRG_PRIOEXECUTION_H

#include <executor/detail/ExecutionBase.h>

#include <chrono>
#include <queue>
#include <utility>

namespace nrg {

struct PrioExecution : detail::ExecutionBase {
    struct QueueElement {
        int prio;
        int id;
        Function what;

        bool operator>(const QueueElement& rhs) const
        {
            return prio > rhs.prio ||
                prio == rhs.prio && id < rhs.id;
        }
      };

    using Queue = std::priority_queue<QueueElement, std::vector<QueueElement>, std::greater<QueueElement>>;

    static void push(Queue& queue, QueueElement elem)
    {
        queue.push(std::move(elem));
    }

    static int next()
    {
        static int nxt = 0;
        return nxt++;
    }

    // 1. no prio (-> 0), fn -> push 1
    template<typename FN>
    static void push(Queue& queue, FN fn)
    {
        QueueElement elem = { 0, next(), std::move(fn) };
        push(queue, std::move(elem));
    }

    // 2. no prio (-> 0), param...
    template<typename FN, typename... Param>
    static void push(Queue& queue, FN fn, Param&&... param)
    {
        QueueElement elem = { 0, next(), [=]() { fn(param...); } };
        push(queue, std::move(elem));
    }

    // 3. prio, fn
    template<typename FN>
    static void push(Queue& queue, int prio, FN fn)
    {
        QueueElement elem = { prio, next(), std::move(fn) };
        push(queue, std::move(elem));
    }

    // 5. prio, param...
    template<typename FN, typename... Param>
    static void push(Queue& queue, int prio, FN fn, Param&&... param)
    {
        QueueElement elem = { prio, next(), [=]() { fn(param...); } };
        push(queue, std::move(elem));
    }

    static bool isEmpty(const Queue& queue)
    {
        return queue.empty();
    }

    static const QueueElement& top(Queue& queue)
    {
        return queue.top();
    }

    static void pop(Queue& queue)
    {
        queue.pop();
    }

    static bool isDue(const QueueElement&)
    {
        return true;
    }

    static void execute(const QueueElement& elem)
    {
        elem.what();
    }

    static std::chrono::steady_clock::duration whenIsDue(const QueueElement& elem)
    {
        return std::chrono::milliseconds(0);
    }
};

}

#endif
